apiVersion: servicecatalog.k8s.io/v1beta1
kind: ClusterServiceBroker
metadata:
  name: ${SERVICE_BROKER_NAME}
  labels:
    app: service-broker
spec:
  url: http://${SERVICE_BROKER_NAME}.${SERVICE_BROKER_NAMESPACE}.svc.cluster.local