id: postgresql
name: postgresql
description: KubeDB managed PostgreSQL
bindable: true
planupdatable: true
metadata:
  displayName: KubeDB managed PostgreSQL
  imageUrl: https://cdn.appscode.com/images/logo/databases/postgresql.png
plans:
- id: demo-postgresql
  name: demo-postgresql
  description: Demo for Standalone PostgreSQL database
  free: true
- id: demo-ha-postgresql
  name: demo-ha-postgresql
  description: Demo for HA PostgreSQL database
  free: true
- id: postgresql
  name: postgresql
  description: Custom PostgreSQL database using user provided PostgresSpec
  free: true
