apiVersion: v1
description: A Helm chart to install service-broker for Kubedb in Kubernetes cluster
name: service-broker
appVersion: "0.1.0"
version: 0.1.0
home: https://github.com/kubedb/service-broker
keywords:
 - Provision
 - Bind
 - Unbind
 - Deprovision
